package game.gui;

public enum GUIScenes {
    RED_REALM_SCENE,GREEN_REALM_SCENE,BLUE_REALM_SCENE,MAGENTA_REALM_SCENE,YELLOW_REALM_SCENE,
    DICE_SCENE,COLOR_PICKER_SCENE,Username_Scene,Player_Selector_Scene,GAME_END;

}
